export default [
  {
    id: 1,
    slug: 'tukang-bangunan',
    title: 'Tukang Bangunan',
    company: 'Bangun Jaya',
    location: 'Jakarta, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Pekerja Kasar',
    bidang: 'Tukang Bangunan',
    posted_at: '2025-02-10T08:00:00Z',
    description:
      'Mencari tukang bangunan yang berpengalaman dalam proyek renovasi rumah.',
    requirements: [
      'Minimal pengalaman 1 tahun dalam konstruksi',
      'Mampu bekerja secara tim',
      'Memiliki alat kerja sendiri (diutamakan)',
    ],
    salary_range: '100,000 - 150,000 IDR/hari',
    benefits: ['Makan siang', 'Transportasi'],
    company_logo: 'https://example.com/logo-tukangbangunan.png',
    apply_link: 'https://example.com/jobs/tukang-bangunan',
  },
  {
    id: 2,
    slug: 'cleaning-service',
    title: 'Cleaning Service',
    company: 'Bersih Bersama',
    location: 'Bandung, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Kebersihan',
    bidang: 'Cleaning Service',
    posted_at: '2025-02-11T09:00:00Z',
    description:
      'Kami membutuhkan tenaga cleaning service untuk membersihkan kantor dan rumah.',
    requirements: [
      'Pengalaman minimal 6 bulan dalam kebersihan',
      'Mampu bekerja cepat dan teliti',
      'Menyukai pekerjaan bersih-bersih',
    ],
    salary_range: '70,000 - 100,000 IDR/hari',
    benefits: ['Makan siang', 'Seragam'],
    company_logo: 'https://example.com/logo-cleaningservice.png',
    apply_link: 'https://example.com/jobs/cleaning-service',
  },
  {
    id: 3,
    slug: 'guru-ngaji',
    title: 'Guru Ngaji',
    company: 'Pesantren Al-Ikhlas',
    location: 'Surabaya, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Pendidikan',
    bidang: 'Guru Ngaji',
    posted_at: '2025-02-12T10:00:00Z',
    description:
      'Kami mencari guru ngaji untuk mengajar anak-anak membaca Al-Quran.',
    requirements: [
      'Hafal minimal 5 juz Al-Quran',
      'Sabar dan ramah terhadap anak-anak',
      'Berpengalaman mengajar ngaji',
    ],
    salary_range: '50,000 - 80,000 IDR/jam',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-gurungaji.png',
    apply_link: 'https://example.com/jobs/guru-ngaji',
  },
  {
    id: 4,
    slug: 'guru-bimbel',
    title: 'Guru Bimbel',
    company: 'Cerdas Mandiri',
    location: 'Yogyakarta, Indonesia',
    employment_type: 'Harian',
    education_level: 'S1',
    jasa: 'Jasa Pendidikan',
    bidang: 'Guru Bimbel',
    posted_at: '2025-02-13T11:00:00Z',
    description:
      'Kami membutuhkan guru bimbel untuk mata pelajaran Matematika dan IPA.',
    requirements: [
      'Minimal lulusan S1 Pendidikan atau MIPA',
      'Mampu menjelaskan materi dengan mudah',
      'Pengalaman mengajar minimal 1 tahun',
    ],
    salary_range: '60,000 - 90,000 IDR/jam',
    benefits: ['Bonus kinerja', 'Modul gratis'],
    company_logo: 'https://example.com/logo-gurubimbel.png',
    apply_link: 'https://example.com/jobs/guru-bimbel',
  },
  {
    id: 5,
    slug: 'bidan-praktek',
    title: 'Bidan Praktek',
    company: 'Klinik Sehat',
    location: 'Bali, Indonesia',
    employment_type: 'Harian',
    education_level: 'D3 Kebidanan',
    jasa: 'Jasa Kesehatan dan Perawatan',
    bidang: 'Bidan',
    posted_at: '2025-02-14T12:00:00Z',
    description: 'Kami membutuhkan bidan untuk praktek di klinik kami.',
    requirements: [
      'Memiliki STR aktif',
      'Pengalaman minimal 2 tahun',
      'Ramah dan sabar terhadap pasien',
    ],
    salary_range: '150,000 - 200,000 IDR/hari',
    benefits: ['Asuransi kesehatan', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-bidan.png',
    apply_link: 'https://example.com/jobs/bidan-praktek',
  },
  {
    id: 6,
    slug: 'perawat-rumah',
    title: 'Perawat Rumah',
    company: 'Care Home',
    location: 'Medan, Indonesia',
    employment_type: 'Harian',
    education_level: 'D3 Keperawatan',
    jasa: 'Jasa Kesehatan dan Perawatan',
    bidang: 'Perawat',
    posted_at: '2025-02-15T13:00:00Z',
    description: 'Kami mencari perawat untuk merawat pasien di rumah.',
    requirements: [
      'Memiliki STR aktif',
      'Pengalaman minimal 1 tahun',
      'Mampu memberikan perawatan medis dasar',
    ],
    salary_range: '120,000 - 180,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-perawat.png',
    apply_link: 'https://example.com/jobs/perawat-rumah',
  },
  {
    id: 7,
    slug: 'fotografer-freelance',
    title: 'Fotografer Freelance',
    company: 'Foto Cemerlang',
    location: 'Semarang, Indonesia',
    employment_type: 'Freelance',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Kreatif',
    bidang: 'Fotografi',
    posted_at: '2025-02-16T14:00:00Z',
    description:
      'Kami mencari fotografer freelance untuk acara pernikahan dan ulang tahun.',
    requirements: [
      'Menguasai teknik fotografi',
      'Memiliki kamera profesional',
      'Portofolio yang menarik',
    ],
    salary_range: '200,000 - 500,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-fotografer.png',
    apply_link: 'https://example.com/jobs/fotografer-freelance',
  },
  {
    id: 8,
    slug: 'tukang-kebun',
    title: 'Tukang Kebun',
    company: 'Hijau Asri',
    location: 'Makassar, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Pekerja Kasar',
    bidang: 'Tukang Kebun',
    posted_at: '2025-02-17T15:00:00Z',
    description:
      'Kami membutuhkan tukang kebun untuk merawat tanaman di rumah dan kantor.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Mampu merawat tanaman hias dan pohon',
      'Memiliki alat kebun sendiri (diutamakan)',
    ],
    salary_range: '80,000 - 120,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-tukangkebun.png',
    apply_link: 'https://example.com/jobs/tukang-kebun',
  },
  {
    id: 9,
    slug: 'penjahit-pakaian',
    title: 'Penjahit Pakaian',
    company: 'Jahit Rapi',
    location: 'Palembang, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Penjahitan',
    bidang: 'Penjahit Pakaian',
    posted_at: '2025-02-18T16:00:00Z',
    description:
      'Kami mencari penjahit pakaian untuk membuat dan memperbaiki pakaian.',
    requirements: [
      'Pengalaman minimal 2 tahun',
      'Menguasai mesin jahit',
      'Teliti dan rapi dalam bekerja',
    ],
    salary_range: '70,000 - 100,000 IDR/hari',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-penjahit.png',
    apply_link: 'https://example.com/jobs/penjahit-pakaian',
  },
  {
    id: 10,
    slug: 'montir-motor',
    title: 'Montir Motor',
    company: 'Bengkel Cepat',
    location: 'Batam, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Perbaikan',
    bidang: 'Montir Motor',
    posted_at: '2025-02-19T17:00:00Z',
    description: 'Kami membutuhkan montir motor untuk servis ringan dan berat.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Menguasai mesin motor injeksi dan karburator',
      'Memiliki alat montir sendiri (diutamakan)',
    ],
    salary_range: '100,000 - 150,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-montirmotor.png',
    apply_link: 'https://example.com/jobs/montir-motor',
  },
  {
    id: 11,
    slug: 'tukang-listrik',
    title: 'Tukang Listrik',
    company: 'Listrik Aman',
    location: 'Pontianak, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Perbaikan',
    bidang: 'Tukang Listrik',
    posted_at: '2025-02-20T18:00:00Z',
    description:
      'Kami mencari tukang listrik untuk instalasi dan perbaikan listrik rumah.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Memahami sistem kelistrikan',
      'Memiliki sertifikat keahlian listrik (diutamakan)',
    ],
    salary_range: '120,000 - 180,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-tukanglistrik.png',
    apply_link: 'https://example.com/jobs/tukang-listrik',
  },
  {
    id: 12,
    slug: 'babysitter',
    title: 'Babysitter',
    company: 'Baby Care',
    location: 'Manado, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Rumah Tangga',
    bidang: 'Pengasuh Anak',
    posted_at: '2025-02-21T19:00:00Z',
    description: 'Kami membutuhkan babysitter untuk merawat bayi dan balita.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Sabar dan telaten',
      'Memahami cara merawat bayi',
    ],
    salary_range: '100,000 - 150,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-babysitter.png',
    apply_link: 'https://example.com/jobs/babysitter',
  },
  {
    id: 13,
    slug: 'pembantu-rumah-tangga',
    title: 'Pembantu Rumah Tangga',
    company: 'Rumah Bersih',
    location: 'Balikpapan, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Rumah Tangga',
    bidang: 'Asisten Rumah',
    posted_at: '2025-02-22T20:00:00Z',
    description:
      'Kami mencari pembantu rumah tangga untuk membersihkan rumah dan memasak.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Mampu bekerja cepat dan teliti',
      'Menyukai pekerjaan rumah tangga',
    ],
    salary_range: '70,000 - 100,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-pembanturumahtangga.png',
    apply_link: 'https://example.com/jobs/pembantu-rumah-tangga',
  },
  {
    id: 14,
    slug: 'supir-pribadi',
    title: 'Supir Pribadi',
    company: 'Drive Safe',
    location: 'Denpasar, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Transportasi dan Logistik',
    bidang: 'Driver Harian',
    posted_at: '2025-02-23T21:00:00Z',
    description:
      'Kami membutuhkan supir pribadi untuk mengantar jemput keluarga.',
    requirements: [
      'Memiliki SIM A/B1',
      'Pengalaman minimal 2 tahun',
      'Menguasai rute kota Denpasar',
    ],
    salary_range: '100,000 - 150,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-supirpribadi.png',
    apply_link: 'https://example.com/jobs/supir-pribadi',
  },
  {
    id: 15,
    slug: 'penjaga-warung',
    title: 'Penjaga Warung',
    company: 'Warung Sehat',
    location: 'Malang, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Kuliner',
    bidang: 'Penjaga Warung',
    posted_at: '2025-02-24T22:00:00Z',
    description: 'Kami mencari penjaga warung untuk melayani pelanggan.',
    requirements: [
      'Pengalaman minimal 6 bulan',
      'Ramah dan cekatan',
      'Mampu menghitung dengan cepat',
    ],
    salary_range: '60,000 - 90,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-penjagawarung.png',
    apply_link: 'https://example.com/jobs/penjaga-warung',
  },
  {
    id: 16,
    slug: 'tukang-saluran-air',
    title: 'Tukang Saluran Air',
    company: 'Air Lancar',
    location: 'Solo, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Perbaikan',
    bidang: 'Tukang Saluran Air',
    posted_at: '2025-02-25T23:00:00Z',
    description:
      'Kami membutuhkan tukang saluran air untuk memperbaiki pipa bocor.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Memahami sistem saluran air',
      'Memiliki alat kerja sendiri (diutamakan)',
    ],
    salary_range: '90,000 - 120,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-tukangsaluranair.png',
    apply_link: 'https://example.com/jobs/tukang-saluran-air',
  },
  {
    id: 17,
    slug: 'penjual-kaki-lima',
    title: 'Penjual Kaki Lima',
    company: 'Warung Goreng',
    location: 'Cirebon, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Kuliner',
    bidang: 'Penjual Kaki Lima',
    posted_at: '2025-02-26T00:00:00Z',
    description: 'Kami mencari penjual kaki lima untuk berjualan gorengan.',
    requirements: [
      'Pengalaman minimal 6 bulan',
      'Mampu bekerja di bawah tekanan',
      'Memiliki kendaraan sendiri (diutamakan)',
    ],
    salary_range: '50,000 - 80,000 IDR/hari',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-penjualkakilima.png',
    apply_link: 'https://example.com/jobs/penjual-kaki-lima',
  },
  {
    id: 18,
    slug: 'penjaga-toko',
    title: 'Penjaga Toko',
    company: 'Toko Bahagia',
    location: 'Pekanbaru, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Retail',
    bidang: 'Penjaga Toko',
    posted_at: '2025-02-27T01:00:00Z',
    description: 'Kami membutuhkan penjaga toko untuk melayani pembeli.',
    requirements: [
      'Pengalaman minimal 6 bulan',
      'Ramah dan cekatan',
      'Mampu menghitung dengan cepat',
    ],
    salary_range: '60,000 - 90,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-penjagatoko.png',
    apply_link: 'https://example.com/jobs/penjaga-toko',
  },
  {
    id: 19,
    slug: 'tukang-cat',
    title: 'Tukang Cat',
    company: 'Cat Indah',
    location: 'Banjarmasin, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Pekerja Kasar',
    bidang: 'Tukang Cat',
    posted_at: '2025-02-28T02:00:00Z',
    description: 'Kami mencari tukang cat untuk mengecat rumah dan gedung.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Menguasai teknik pengecatan',
      'Memiliki alat kerja sendiri (diutamakan)',
    ],
    salary_range: '80,000 - 120,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-tukangcat.png',
    apply_link: 'https://example.com/jobs/tukang-cat',
  },
  {
    id: 20,
    slug: 'kurir-barang',
    title: 'Kurir Barang',
    company: 'Express Delivery',
    location: 'Ambon, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Transportasi dan Logistik',
    bidang: 'Kurir',
    posted_at: '2025-03-01T03:00:00Z',
    description:
      'Kami membutuhkan kurir barang untuk mengantar paket ke pelanggan.',
    requirements: [
      'Memiliki SIM C',
      'Pengalaman minimal 6 bulan',
      'Menguasai rute kota Ambon',
    ],
    salary_range: '70,000 - 100,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-kurirbarang.png',
    apply_link: 'https://example.com/jobs/kurir-barang',
  },
  {
    id: 21,
    slug: 'makeup-artist',
    title: 'Makeup Artist',
    company: 'Beauty Studio',
    location: 'Jakarta, Indonesia',
    employment_type: 'Freelance',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Kecantikan',
    bidang: 'Makeup Artist',
    posted_at: '2025-03-02T04:00:00Z',
    description:
      'Kami mencari makeup artist untuk acara pernikahan dan wisuda.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Memiliki portofolio yang menarik',
      'Menguasai teknik makeup natural dan bold',
    ],
    salary_range: '200,000 - 500,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-makeupartist.png',
    apply_link: 'https://example.com/jobs/makeup-artist',
  },
  {
    id: 22,
    slug: 'hair-stylist',
    title: 'Hair Stylist',
    company: 'Salon Glamour',
    location: 'Bandung, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Kecantikan',
    bidang: 'Hair Stylist',
    posted_at: '2025-03-03T05:00:00Z',
    description: 'Kami membutuhkan hair stylist untuk salon kecantikan.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Menguasai teknik potong dan styling rambut',
      'Ramah dan komunikatif',
    ],
    salary_range: '80,000 - 120,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-hairstylist.png',
    apply_link: 'https://example.com/jobs/hair-stylist',
  },
  {
    id: 23,
    slug: 'spa-therapist',
    title: 'Spa Therapist',
    company: 'Relax Spa',
    location: 'Bali, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Kecantikan',
    bidang: 'Spa Therapist',
    posted_at: '2025-03-04T06:00:00Z',
    description:
      'Kami mencari spa therapist untuk memberikan layanan pijat dan relaksasi.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Menguasai teknik pijat tradisional dan modern',
      'Ramah dan profesional',
    ],
    salary_range: '100,000 - 150,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-spatherapist.png',
    apply_link: 'https://example.com/jobs/spa-therapist',
  },
  {
    id: 24,
    slug: 'laundry-service',
    title: 'Laundry Service',
    company: 'Cuci Bersih',
    location: 'Surabaya, Indonesia',
    employment_type: 'Harian',
    education_level: 'SMP',
    jasa: 'Jasa Kebersihan',
    bidang: 'Laundry Service',
    posted_at: '2025-03-05T07:00:00Z',
    description:
      'Kami membutuhkan tenaga laundry untuk mencuci dan menyetrika pakaian.',
    requirements: [
      'Pengalaman minimal 6 bulan',
      'Mampu bekerja cepat dan teliti',
      'Menyukai pekerjaan bersih-bersih',
    ],
    salary_range: '70,000 - 100,000 IDR/hari',
    benefits: ['Makan siang', 'Bonus kinerja'],
    company_logo: 'https://example.com/logo-laundryservice.png',
    apply_link: 'https://example.com/jobs/laundry-service',
  },
  {
    id: 25,
    slug: 'event-organizer',
    title: 'Event Organizer',
    company: 'Event Pro',
    location: 'Yogyakarta, Indonesia',
    employment_type: 'Freelance',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Event dan Hiburan',
    bidang: 'Event Organizer',
    posted_at: '2025-03-06T08:00:00Z',
    description:
      'Kami mencari event organizer untuk mengatur acara pernikahan dan ulang tahun.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Kreatif dan inovatif',
      'Mampu bekerja dalam tim',
    ],
    salary_range: '200,000 - 500,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-eventorganizer.png',
    apply_link: 'https://example.com/jobs/event-organizer',
  },
  {
    id: 26,
    slug: 'mc-acara',
    title: 'MC (Master of Ceremony)',
    company: 'Voice Talent',
    location: 'Semarang, Indonesia',
    employment_type: 'Freelance',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Event dan Hiburan',
    bidang: 'MC',
    posted_at: '2025-03-07T09:00:00Z',
    description: 'Kami mencari MC untuk memandu acara pernikahan dan seminar.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Komunikatif dan percaya diri',
      'Mampu menguasai panggung',
    ],
    salary_range: '150,000 - 300,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-mc.png',
    apply_link: 'https://example.com/jobs/mc-acara',
  },
  {
    id: 27,
    slug: 'konsultan-bisnis',
    title: 'Konsultan Bisnis',
    company: 'Biz Consult',
    location: 'Makassar, Indonesia',
    employment_type: 'Freelance',
    education_level: 'S1',
    jasa: 'Jasa Konsultasi',
    bidang: 'Konsultan Bisnis',
    posted_at: '2025-03-08T10:00:00Z',
    description:
      'Kami membutuhkan konsultan bisnis untuk membantu pengembangan usaha.',
    requirements: [
      'Pengalaman minimal 2 tahun',
      'Memiliki pemahaman tentang strategi bisnis',
      'Mampu memberikan solusi praktis',
    ],
    salary_range: '500,000 - 1,000,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-konsultanbisnis.png',
    apply_link: 'https://example.com/jobs/konsultan-bisnis',
  },
  {
    id: 28,
    slug: 'konsultan-keuangan',
    title: 'Konsultan Keuangan',
    company: 'Finance Pro',
    location: 'Batam, Indonesia',
    employment_type: 'Freelance',
    education_level: 'S1',
    jasa: 'Jasa Konsultasi',
    bidang: 'Konsultan Keuangan',
    posted_at: '2025-03-09T11:00:00Z',
    description:
      'Kami mencari konsultan keuangan untuk membantu manajemen keuangan perusahaan.',
    requirements: [
      'Pengalaman minimal 2 tahun',
      'Memiliki sertifikasi keuangan (diutamakan)',
      'Mampu memberikan analisis keuangan',
    ],
    salary_range: '500,000 - 1,000,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-konsultankeuangan.png',
    apply_link: 'https://example.com/jobs/konsultan-keuangan',
  },
  {
    id: 29,
    slug: 'videografi',
    title: 'Videografi',
    company: 'Video Vision',
    location: 'Pontianak, Indonesia',
    employment_type: 'Freelance',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Kreatif',
    bidang: 'Videografi',
    posted_at: '2025-03-10T12:00:00Z',
    description:
      'Kami mencari videografer untuk acara pernikahan dan dokumentasi.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Memiliki kamera dan peralatan editing',
      'Portofolio yang menarik',
    ],
    salary_range: '200,000 - 500,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-videografi.png',
    apply_link: 'https://example.com/jobs/videografi',
  },
  {
    id: 30,
    slug: 'desain-grafis',
    title: 'Desain Grafis',
    company: 'Creative Design',
    location: 'Manado, Indonesia',
    employment_type: 'Freelance',
    education_level: 'SMA/SMK',
    jasa: 'Jasa Kreatif',
    bidang: 'Desain Grafis',
    posted_at: '2025-03-11T13:00:00Z',
    description:
      'Kami mencari desainer grafis untuk membuat logo dan materi promosi.',
    requirements: [
      'Pengalaman minimal 1 tahun',
      'Menguasai Adobe Photoshop dan Illustrator',
      'Portofolio yang menarik',
    ],
    salary_range: '200,000 - 500,000 IDR/proyek',
    benefits: ['Bonus kinerja'],
    company_logo: 'https://example.com/logo-desaingrafis.png',
    apply_link: 'https://example.com/jobs/desain-grafis',
  },
];
